### ISSUE TITLE
You don't seem to have a generator with the name angular:common

### ISSUE THREAD

**Issue by archit2u** [yeoman/generator-angular#1239] opened 2015-12-27 18:39 UTC
Hi,

As soon as I run ```yo angular``` I get the following error

```
? Would you like to use Gulp (experimental) instead of Grunt? Yes
? Would you like to use Sass? Yes
? Would you like to include Bootstrap? No
? Which modules would you like to include? angular-animate.js, angular-cookies.j   create app/styles/main.scssr-route.js, angular-sanitize.js, angular-touch.js
   create app/index.html
   create bower.json
   create .bowerrc
   create package.json
   create gulpfile.js
   create README.md
Error angular 

You don't seem to have a generator with the name angular:common:/usr/local/lib/node_modules/generator-angular/app/index.js installed.

You can see available generators with npm search yeoman-generator and then install them with npm install [name].
```
I also ran ```yo doctor``` and every thing is fine with it. Any help would be appreciated. 
node version: 5.2.0
npm version: 3.5.2 
Thanks

**Comment by Rubyeyes** [comment] 2015-12-27 19:31
I got the same error here.

**Comment by beenetto** [comment] 2015-12-27 21:00
Same here.

**Comment by jonje** [comment] 2015-12-28 01:00
Same issue but 
Node version: 5.3.0
Npm version: 3.3.12

**Comment by Spasms** [comment] 2015-12-28 01:55
Same issue here.

**Comment by charlie-gbox** [comment] 2015-12-28 03:06
same for me

**Comment by roaks3** [comment] 2015-12-28 07:10
I think this is related to this change in yeoman-environment: https://github.com/yeoman/environment/commit/945878b5f058091f1351f4c3eaddb454ce296f95.  It looks like 1.5.0 was released recently, which also gets used if you try an older version of ```yo``` because of the ```^``` dependency resolution.

As I understand the problem, more than one ```:``` is no longer allowed in the generator name, but the current yeoman-generator version that is being used here still appends a ```:<resolved-path>``` to the name.  This appears fixed in a later version of yeoman-generator (https://github.com/yeoman/generator/pull/471), but I'm not sure if it would be safe to bump that library.

Here is a very hacky way to get it working for now:
- Edit the dependency in ```/usr/local/lib/node_modules/yo/package.json``` to be ```"yeoman-environment": "1.4.0"```
- ```cd /usr/local/lib/node_modules/yo```
- ```rm -rf node_modules```
- ```npm install```

**Comment by rof20004** [comment] 2015-12-28 07:20
Same problem here, after updated some packages with npm install.

**Comment by rohit-creo** [comment] 2015-12-28 10:10
I got the same error.

**Comment by bartosss** [comment] 2015-12-28 12:06
same here. worked on this for hours but it's a yeoman bug.

**Comment by immortalcy** [comment] 2015-12-28 13:46
Has anyone found a solution/workaround on this problem yet? I get the following error when running yo angular:route:

You don't seem to have a generator with the name angular:controller:/usr/local/lib/node_modules/generator-angular/route/index.js installed.
You can see available generators with npm search yeoman-generator and then install them with npm install [name].
To see the 15 registered generators run yo with the `--help` option.

However when I run the command separately it works just fine.

**Comment by rof20004** [comment] 2015-12-28 13:49
separately how ?

**Comment by immortalcy** [comment] 2015-12-28 13:49
when I run `yo angular:view <name>` and yo `angular:controller <name>`

**Comment by rof20004** [comment] 2015-12-28 13:50
can you run yo angular ?

Here i can not create angular project because this error.

**Comment by immortalcy** [comment] 2015-12-28 13:51
`yo angular` works fine

**Comment by rohit-creo** [comment] 2015-12-28 14:01
I cannot create project with yo angular

**Comment by rohit-creo** [comment] 2015-12-28 14:04
yo angular
Out of the box I include Bootstrap and some AngularJS recommended modules.

? Would you like to use Gulp (experimental) instead of Grunt? Yes
? Would you like to use Sass? Yes
? Would you like to include Bootstrap? Yes
? Which modules would you like to include? angular-animate.js, angular-cookies.js, angular-resource.js, angular-route.js
   create app\styles\main.scss-touch.js
   create app\index.html
   create bower.json
   create .bowerrc
   create package.json
   create gulpfile.js
   create README.md
Error angular

You don't seem to have a generator with the name angular:common:C:\Users\rohit\AppData\Roaming\npm\node_modules\generator-angular\app\index.js installed.
You can see available generators with npm search yeoman-generator and then install them with npm install [name].
To see the 15 registered generators run yo with the `--help` option.

**Comment by rof20004** [comment] 2015-12-28 14:05
yeah, same error for many people, I am waiting for developers correct this.

**Comment by immortalcy** [comment] 2015-12-28 14:05
And you just downloaded and installed yeoman?? I just updated to the latest version while I was working and then I received that error.

**Comment by rohit-creo** [comment] 2015-12-28 14:07
Yes yeoman is new install on this machine.

**Comment by rof20004** [comment] 2015-12-28 14:07
Mee too, i was using normaly, then I updated and not working more.

**Comment by dean-me** [comment] 2015-12-28 14:15
I had posted same same issue on the Yeoman issue tracker. Same prob:
https://github.com/yeoman/yeoman/issues/1580

**Comment by bartosss** [comment] 2015-12-28 14:41
I solved this with using an older version. npm install -g generator-angular@0.5.0

**Comment by archit2u** [comment] 2015-12-28 14:45
@bartosss But 0.5.0 is quiet old. The latest is 0.15.1.

**Comment by larsdecker** [comment] 2015-12-28 14:46
I have the same issue. Anyone else have a good solution that works? How can a install an old version of the angular generator?

**Comment by rof20004** [comment] 2015-12-28 14:50
@bartosss posted the workaround, above.

I will try install the same version 0.5.0 tonight.

**Comment by immortalcy** [comment] 2015-12-28 14:51
@bartosss I tired using v0.5.0 but nothing works.

**Comment by 3KyNoX** [comment] 2015-12-28 14:58
Same prob here dudes : https://github.com/yeoman/yo/issues/396

**Comment by elodlukacs** [comment] 2015-12-28 16:03
Yeah, same here. Nothing helped, I tried a lot things found on stackoverflow but without success.

**Comment by mkjsix** [comment] 2015-12-28 16:33
+1

**Comment by roaks3** [comment] 2015-12-28 17:15
My solution should work if you just need to get the generator working (it's working for me now), although the path will need to match what you see in the error message after ```angular:common:```.  The only other workaround I can think of would be to use much older versions of yo and generator-angular, but you would need to make sure the versions are compatible.

**Comment by bartosss** [comment] 2015-12-28 17:31
It worked for me with using an older version of generator-angular. First delete what you already have and install the older version.

**Comment by Spasms** [comment] 2015-12-28 17:45
@roaks3 That didn't work for me. I get this error when I try to `npm install` from the yo directory:

```
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/Users/home/.npm-packages/bin/npm" "install"
npm ERR! node v4.2.4
npm ERR! npm  v3.5.2
npm ERR! Cannot read property 'target' of null
```

**Comment by jonje** [comment] 2015-12-28 21:27
@roaks3 your solution did not work for me. @bartosss what version did you go with?

**Comment by 3KyNoX** [comment] 2015-12-28 21:40
@roaks3 Did not worked for me either. Using win10 x64 (in C:\Users\my_name\AppData\Roaming\npm\node_modules\yo).

Except folder location, I did exactly what you said.

**Comment by aitoraznar** [comment] 2015-12-28 21:42
FYI
The @roaks3  solution works in linux (node 5.0.0, npm 3.3.6) and not in mac(node 4.2.1, npm 3.5.2)

In mac I have https://github.com/npm/npm/issues/10686

**Comment by mkjsix** [comment] 2015-12-28 22:12
Somebody knows which was the last working version of this generator to install? On a Mac I have the same issue as @aitoraznar. I even tried to run yo via a docker image (https://hub.docker.com/r/cthulhu666/yeoman/) but this issue is present also there.

**Comment by americoneto1** [comment] 2015-12-28 22:23
The @roaks3 works for me in windows 7 (node 4.2.2).

**Comment by ftheomunhoz** [comment] 2015-12-28 22:41
+1

**Comment by xinmeng1** [comment] 2015-12-28 22:48
same issue, I think this problem maybe caused by install generator-angular with he error: 

https://github.com/yeoman/generator-angular/issues/1192

When I install generator-angular@0.11.1 then
1) UNMET PEER DEPENDENCY generator-karma@>=0.9.0
2) UNMET PEER DEPENDENCY yo@>=1.0.0
When I install generator-angular then
1) UNMET PEER DEPENDENCY generator-karma@>=0.9.0

**Comment by georaldc** [comment] 2015-12-28 23:12
@xinmeng1 I don't think your error isn't related to the issue being discussed here, which is about what @roaks3 explains above

**Comment by edermaxc** [comment] 2015-12-28 23:47
+1

**Comment by jonje** [comment] 2015-12-29 01:36
Has anyone come up with a solution for Macs?

**Comment by alexishida** [comment] 2015-12-29 02:04
same for me

**Comment by georaldc** [comment] 2015-12-29 02:17
It doesn't seem to be a mac and/or windows issue only because I run into the same problem too with an ubuntu box using virtualbox. Tested on both node 4 and 5.

**Comment by kseb** [comment] 2015-12-29 02:27
same for me, under os x.

**Comment by rof20004** [comment] 2015-12-29 02:49
I tested @roaks3 solution but not worked for me.

I use O.S Debian Jessie 8.2 amd64 with multiarch configured
Kernel 3.16

**Comment by Robinyo** [comment] 2015-12-29 04:31
same for me, on OS X Yosemite:

$ node --version && npm --version
v5.3.0
3.5.3

$ yo --version
1.5.1

$ yo angular

     _-----_
    |       |    .--------------------------.
    |--(o)--|    |    Welcome to Yeoman,    |
   `---------´   |   ladies and gentlemen!  |
    ( _´U`_ )    '--------------------------'
    /___A___\    
     |  ~  |     
   __'.___.'__   
 ´   `  |° ´ Y ` 

Out of the box I include Bootstrap and some AngularJS recommended modules.

? Would you like to use Gulp (experimental) instead of Grunt? No
? Would you like to use Sass (with Compass)? Yes
? Would you like to include Bootstrap? Yes
? Would you like to use the Sass version of Bootstrap? Yes
? Which modules would you like to include? angular-animate.js, angular-cookies.js, angular-resource.js, angular-rou   create app/styles/main.scssgular-touch.js
   create app/index.html
   create bower.json
   create .bowerrc
   create package.json
   create Gruntfile.js
   create README.md
Error angular 

You don't seem to have a generator with the name angular:common:/usr/local/lib/node_modules/generator-angular/app/index.js installed.
You can see available generators with npm search yeoman-generator and then install them with npm install [name].
To see the 19 registered generators run yo with the `--help` option.

**Comment by LeCanardNoir** [comment] 2015-12-29 05:00
same thing for me,... i try every

I need this tool ,... :(

**Comment by MaksTsk** [comment] 2015-12-29 05:19
+1 
Ubuntu 15.04
```
$ node --version && npm --version
v5.3.0
3.5.3
```
```
$ yo --version
1.5.1
```
The same error

**Comment by SBoudrias** [comment] 2015-12-29 06:10
@roaks3 thanks for investigating!! This is a very specific combination of versions causing that bug...

Could someone try to update generator-angular to yeoman-generator 0.18 and see if it works? (this is the last version without us starting to deprecate old API)

**Comment by rohit-creo** [comment] 2015-12-29 06:51
I tired using v0.5.0 but same error

**Comment by elodlukacs** [comment] 2015-12-29 07:21
When I'm trying @roaks3 solution I got this error msg:

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Humbak Juli\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v5.3.0
npm ERR! npm  v3.5.2

npm ERR! Cannot read property 'target' of null
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Humbak Juli\AppData\Roaming\npm\node_modules\yo\npm-debug.log

**Comment by artdias90** [comment] 2015-12-29 07:39
Same error here

**Comment by fk-mbc** [comment] 2015-12-29 08:44
The interim solution from @roaks3 works for me on Windows 10.

As he describes, you have to edit:
*C:\Users\YOURUSERNAME\AppData\Roaming\npm\node_modules\yo\package.json* on line 71 with
```
71    "yeoman-environment": "1.4.0",
```
then delete the node_modules folder inside the yo directory and reinstall the dependencies with
```
npm install
```
from a console window.

**Comment by 3KyNoX** [comment] 2015-12-29 09:43
Finally, I did @roaks3 workaround another time, (I have forgotting remove the ^ in *"yeoman-environment": "1.4.0"* first time) and that's work now.

**Comment by immortalcy** [comment] 2015-12-29 10:03
@roaks3 @3KyNoX Yes I confirm as well that if you remove the ^ and change the version to 1.4.0 it works perfectly.

**Comment by IrynaBu** [comment] 2015-12-29 10:17
@immortalcy Try to update Node.js. This solution works for me after update

**Comment by javi-rmrz** [comment] 2015-12-29 12:00
Was having the same problem using OS X 10.10.5 Yosemite and node v5.2.0 + npm v3.3.12
Output from ```yo angular```:

```
(...)
Error angular 

You don't seem to have a generator with the name angular:common:/usr/local/lib/node_modules/generator-angular/app/index.js installed.
You can see available generators with npm search yeoman-generator and then install them with npm install [name].
To see the 16 registered generators run yo with the `--help` option.
```

Did @roaks3's workaround, working just fine now. Thanks!

**Comment by americoneto1** [comment] 2015-12-29 12:43
@SBoudrias Changing yeoman-generator version to 0.18.0, this issue was fixed, but another problem appear when invoke karma:app is called.

```
You don't seem to have a generator with the name karma:app installed.
```

```javascript
this.invoke('karma:app', {
      options: {
        'skip-install': this.options['skip-install'],
        'base-path': '../',
        'coffee': this.options.coffee,
        'travis': true,
        'files-comments': bowerComments.join(','),
        'app-files': 'app/scripts/**/*.' + jsExt,
        'test-files': [
          'test/mock/**/*.' + jsExt,
          'test/spec/**/*.' + jsExt
        ].join(','),
        'bower-components-path': 'bower_components'
      }
    });
```

It´s seems to be related to deprecated method "invoke". We have to replace invoke to composeWith.

**Comment by rof20004** [comment] 2015-12-29 12:44
I will try tonigth, thanks for sharing.

**Comment by TuiLaHiep** [comment] 2015-12-29 15:58
Same problem here

**Comment by alexpica** [comment] 2015-12-29 17:24
+1

**Comment by fabiopaiva** [comment] 2015-12-29 17:46
npm 3 don't install dependencies directly, then install boths in same command:

    sudo npm install generator-karma generator-angular -g

**Comment by oceanwap** [comment] 2015-12-29 18:01
Thought I am alone facing this problem.

**Comment by ppwalks24** [comment] 2015-12-29 18:13
Today is the first day i'm learning angualr through a book, chapter 1 yo angular appname ---- a great first experience, full day and learnt virtualy nothing..

**Comment by juansss** [comment] 2015-12-29 18:14
Hahahaha same here!....

**Comment by ppwalks24** [comment] 2015-12-29 18:16
I been developing php for 4-5 yrs, worked with most mvc frameworks commercialy and can't even get this running what a joke..

**Comment by techneo1** [comment] 2015-12-29 18:52
@roaks3: thanks bro :)
It worked!! :+1:

**Comment by bartosss** [comment] 2015-12-29 19:26
@ppwalks24 haha I got the same feeling. Eventually it was not my fault, which is better 😅

**Comment by fabiopaiva** [comment] 2015-12-29 19:37
@roaks3 don't work to me

**Comment by relicta** [comment] 2015-12-29 20:22
Someone please fix this

**Comment by rof20004** [comment] 2015-12-29 21:08
@ppwalks24 I started to learn too, but it is not my fault too, hehehehe :dancer:

**Comment by williamnoto** [comment] 2015-12-29 21:27
Struggling with same. Roaks3's fix didn't work for me perhaps because I used the homebrew method of installing node? Attempted changing the environment var to 1.4.0 in ~/.npm but no luck. Please resolve!

**Comment by mywebdrag** [comment] 2015-12-29 22:15
@williamnoto , I have the same problem, Followed the steps by Roaks3 but did not work. enviroment is OSX/Homebrew

**Comment by SBoudrias** [comment] 2015-12-29 23:15
# Reinstall yo and the issue should be fixed

I unpublished the problematic version of yeoman-environment. We'll work on a correct fix eventually.

**Closed by SBoudrias** 2015-12-29 23:15 UTC

**Comment by rof20004** [comment] 2015-12-29 23:18
Thanks @SBoudrias

**Comment by rof20004** [comment] 2015-12-29 23:44
@SBoudrias sorry for question, but how can i reinstall yo ?

I tried npm install -g yo@latest

But the version not change and the error continue.

Can you help me ?

I am new in yeoman, I am studying.

**Comment by SBoudrias** [comment] 2015-12-29 23:50
@rof20004 

```
npm uninstall yo
npm install yo
```

**Comment by rof20004** [comment] 2015-12-29 23:51
hehe, thanks.

**Comment by danielkim85** [comment] 2015-12-30 00:03
Hi,
I just tried fresh installing yo, and the reported issue has not been fixed.

**Comment by S1riU5** [comment] 2015-12-30 00:12
same here

**Comment by Aerion** [comment] 2015-12-30 00:13
Same here, uninstalled yo and re-installed it, still the same error.
node 5.3.0; npm 3.5.2; yo 1.5.1

**Comment by rof20004** [comment] 2015-12-30 00:14
Well, me too. I tried first npm install, than later npm uninstall and install, but not working yet.

**Comment by IckleChris** [comment] 2015-12-30 00:39
+1 still an issue after fresh Yeoman install (Node 5.3.0, NPM 3.3.12, yo 1.5.1)

**Comment by williamnoto** [comment] 2015-12-30 00:47
Do we need to clear cache?

**Comment by Ariel-Isaacm** [comment] 2015-12-30 00:49
Same here

**Comment by IckleChris** [comment] 2015-12-30 01:10
@williamnoto cleared cache during fresh install to no avail

**Comment by williamnoto** [comment] 2015-12-30 01:30
No luck on my end either. FWIW, I double checked the package.json file after doing npm uninstall yo && nam install yo -g and saw the yeoman-environment was set to "^1.2.7" After that didn't work, (same errors as before) I tried removing the carrot to "1.2.7" but still no love...

**Comment by williamnoto** [comment] 2015-12-30 01:35
@SBoudrias doesn't seem closed... :(

**Comment by SBoudrias** [comment] 2015-12-30 01:45
Try again now, I think I didn't unpublished correctly.

**Comment by IckleChris** [comment] 2015-12-30 01:48
Yep, that's sorted it for me @SBoudrias cheers :+1:

**Comment by Fudra** [comment] 2015-12-30 02:19
Works perfectly! Thanks @SBoudrias ;)

**Comment by williamnoto** [comment] 2015-12-30 02:52
Working great... Thanks, @SBoudrias.

**Comment by Ariel-Isaacm** [comment] 2015-12-30 02:53
Worked great :)! @SBoudrias

**Comment by rof20004** [comment] 2015-12-30 04:28
Well done, thanks @SBoudrias .

**Comment by LeCanardNoir** [comment] 2015-12-30 04:32
npm uninstall -g yo && npm install -g yo 

Work for me,
Thanks @SBoudrias

**Comment by benroo** [comment] 2015-12-30 06:14
Worked for me too, thanks @SBoudrias !

**Comment by artdias90** [comment] 2015-12-30 06:54
finally working again..

**Comment by SBoudrias** [comment] 2015-12-30 09:06
@americoneto1 any help to update the generator to at least 0.18 is welcome. This is way overdue and I'm not sure anyone on the core team really have time to undertake what this requires.

I just updated the full test suite so it plays nicely when we try to bump the version. We'll mostly need to refactor some code and fix the bugs who'll be rising in generator-angular because of the changes we did on yeoman-generator.

Really, help from anyone here is more than welcomed.

**Comment by S1riU5** [comment] 2015-12-30 17:28
@SBoudrias Thx for this fix

**Comment by Bouhnosaure** [comment] 2015-12-31 01:14
THANKS !

**Comment by aurerua** [comment] 2015-12-31 13:08
@SBoudrias Thanks for the fix! :)

**Comment by Petya-Naumova** [comment] 2016-01-05 21:38
@SBoudrias, this fix did not work for me, unfortunately.

**Comment by SBoudrias** [comment] 2016-01-05 21:51
@Petya-Naumova then you're either not having this issue, or you did not correctly uninstalled `yo`.

**Comment by Petya-Naumova** [comment] 2016-01-06 20:23
@SBoudrias, oh, so it's not to install the missing generator manually?

**Comment by rocket13531** [comment] 2016-01-07 20:30
npm WARN EPEERINVALID generator-angular@0.15.1 requires a peer of generator-karma@>=0.9.0 but none was installed.

**Comment by rof20004** [comment] 2016-01-07 20:33
This is only warning message, I think you can try using normaly to see if it works, maybe your tests not work. I do not use karma tests, then i ignore this message all the time, it's show to me too.

**Comment by boxhead201** [comment] 2016-01-08 08:37
I am still being hit with this issue.  I spent a couple of hours on this to no avail.

Node v4.2.4
npm 3.5.3
yo 1.6.0

**Comment by dangt85** [comment] 2016-01-08 17:10
This is still an issue for me as well. I'm on Windows 8.1

node -v
v4.2.2
npm -v
3.5.3

I believe the issue in Windows is that the path is too long.

**Comment by SBoudrias** [comment] 2016-01-08 19:19
Are you sure you're having the exact same issue?

**Comment by SBoudrias** [comment] 2016-01-08 21:05
The bug apparently wasn't fix on windows. It should be now. `npm -g update yo`

**Comment by dangt85** [comment] 2016-01-08 23:00
It's still not working... I'll try on linux, but here's my error (Windows 8.1 PowerShell - Admin)
yo --version 
1.6.0

![image](https://cloud.githubusercontent.com/assets/68380/12211795/b69594fa-b631-11e5-8256-b1349e85d44c.png)

**Comment by MaximilianoRios** [comment] 2016-01-09 02:22
Still having the same issue after trying all the solutions here, I'm using Windows 7

**Comment by rof20004** [comment] 2016-01-09 17:40
I installed two weeks ago in my work, on windows 7 64 bit, everything works perfect.

**Comment by MaximilianoRios** [comment] 2016-01-09 17:42
Well, after trying many things it only worked after installing karma, even when it's only a warning it seems to be necessary to make it work.
Thanks to everyone.

**Comment by demaniak** [comment] 2016-01-09 21:18
Every gorram time I touch this stuff there is some fresh hell to work around.

In my past experience, uninstalling everything, then installing all the latest versions of everything (and making sure you update everything to the latest versions after the initial install), AND then sometimes just starting your project from scratch...then sometimes you get lucky and things actually work.

But, then, to put the cherry on this mountain of fun...after you get this all working, and you leave the project for a couple of months, when you get back ,and try to build....guess what? Chances are, something brakes again. 
In which case, I advise you to try the uninstall-install-update-retry circus mentioned above.

**Comment by 47ronin** [comment] 2016-01-12 00:48
This appears to be fixed in Yeoman 1.6.0. `npm install -g yo` then :pray: that it works, have some :coffee:, then when it finishes, try `yo angular` —succeeded here on Mac OS X 10.11.2, Node 5.4.0, npm 3.3.12.

**Comment by seanhastings** [comment] 2016-01-23 21:44
Had the same issue even after uninstalling and reinstalling yo, only thing that got me up and running was `npm install -g generator-karma`

**Comment by sumitsharma0999** [comment] 2016-01-24 18:21
+1, still hitting the same issue, 

@seanhastings solution worked for me

**Comment by patrickhofer** [comment] 2016-01-26 11:11
I still get `UNMET PEER DEPENDENCY generator-karma@>=0.9.0` when i run `npm install -g generator-angular` @seanhastings solution didn't work for me.

**Comment by rof20004** [comment] 2016-01-26 11:46
@patrickhofer Generally it is only warning, you can ignore, but if you want solve this warnings, I do not know why, but install everything in on line solve.

**Comment by Petya-Naumova** [comment] 2016-01-26 12:21
npm install -g generator-karma

On Jan 26, 2016 1:11 PM, "Patrick Hofer" <notifications@github.com> wrote:
>
> I still get UNMET PEER DEPENDENCY generator-karma@>=0.9.0 when i run npm
install -g generator-angular @seanhastings solution didn't work for me.

**Comment by QCCS** [comment] 2016-03-12 16:05
@SBoudrias  solution didn't work for me.

**Comment by Petya-Naumova** [comment] 2016-03-12 20:39
Try this :
npm install -g generator-karma

**Comment by liorboord** [comment] 2016-03-30 11:04
what do you get when you type:

`yo --generators`

? do you not see your recently installed generators in the list?

I had the above issue on Ubuntu using nvm, eventually I figured out that yo was pointing to an older version of yoeman on my computer. I removed an old 'node_modules' library and reinstalled yoeman. Now yo points to my nvm library.

**Comment by BassemGhoniem** [comment] 2016-04-15 10:15
I faced the same problem, but It finally worked by using
`sudo yo angular`

It didn't work for me with `yo angular` only

**Comment by eddiemonge** [comment] 2016-04-15 20:32
you should never really be using sudo with yo

**Comment by nickylimjj** [comment] 2016-07-01 17:29
I'm getting the following error after generating with generator-angular

```javascript
Running "concurrent:server" (concurrent) task
    Warning: Running "compass:server" (compass) task
    Warning: not found: compass Use --force to continue.
    
    Aborted due to warnings.
````

Any idea? I have even installed compass globally

**Comment by SBoudrias** [comment] 2016-07-01 17:34
@nickylimjj can you run `compass` yourself in your terminal? Looks like it might not be into your system PATH.

**Comment by nickylimjj** [comment] 2016-07-01 17:50
@SBoudrias thanks but is it an executable? i checked my globally installed npm-packages and compass does not have any binaries shouldn't it just be a dependency for my generated angular app? Thanks

**Comment by georaldc** [comment] 2016-07-01 17:55
@nickylimjj make sure you have ruby installed, then get compass via ```gem install compass```

**Comment by ignacio-chiazzo** [comment] 2016-08-13 14:30
I am having the same issue, MAC OS, EL Captian 10.11.5. 
Node v 5.5.0
Tried to uninstall yo and install and it didn't work.

**Comment by yy-hh** [comment] 2016-08-31 06:24
俺也是啊

**Comment by theasimzaidi** [comment] 2016-09-10 20:35
SOLUTION:

First you must run 

npm install --global yo

Then you can run:

yo angular

After that you want to run this for your npm dependencies:

npm install

**Comment by redcomethk** [comment] 2016-09-27 01:58
Turns out re-installing yo works for me. But the original yo file should be removed first.
I first run a `which yo` to find out the location of the yo file, remove it.
Then I run 
`npm remove -g yo`
`npm install -g yo`
And then my problem is gone.

**Comment by phdowling** [comment] 2016-10-15 14:09
Issue persists. I'm on Mac OS 10.10.5, installed using `npm install -g yo generator-karma generator-express-angular`
