### ISSUE TITLE
'yo angular' not working after upgrading to yo v1.4.0

### ISSUE THREAD

**Issue by janaaronlee** [yeoman/generator-angular#967] opened 2015-01-08 11:45 UTC
```
$ yo --version
1.4.0
```
```
$ yo angular
Error angular 

You don't seem to have a generator with the name angular installed.
You can see available generators with npm search yeoman-generator and then install them with npm install [name].
To see the 15 registered generators run yo with the `--help` option.
$ yo
? 'Allo Jan! What would you like to do? (Use arrow keys)
  Run a generator
❯ Angular 
  Karma 
  ──────────────
  Update your generators 
  Install a generator 
  Find some help 
  Get me out of here! 
  ──────────────
```

**Comment by gablabelle** [comment] 2015-01-08 14:41
Same problem here ... ran 'yo' chose > Angular and was able to go through.

**Comment by janaaronlee** [comment] 2015-01-08 14:47
Reverted back to v1.3.3 in the meantime

**Comment by eddiemonge** [comment] 2015-01-08 19:02
duplicate of https://github.com/yeoman/yo/issues/264 yo has been degraded for now.

**Closed by eddiemonge** 2015-01-08 19:02 UTC
