### ISSUE TITLE
Not including Bower CSS

### ISSUE THREAD

**Issue by mohislm** [yeoman/generator-angular#1120] opened 2015-06-19 15:49 UTC
When scaffolding (`yo angular`) with Bootstrap, the bootstrap css is not included in the bower:css section of index.html file.
```
    <!-- build:css(.) styles/vendor.css -->
    <!-- bower:css -->
    <!-- endbower -->
    <!-- endbuild -->
```
Also, after instaling npm and bower dependencies, the command line hangs forever:
```
...
grunt-google-cdn@0.4.3 node_modules/grunt-google-cdn
├── chalk@0.5.1 (ansi-styles@1.1.0, escape-string-regexp@1.0.3, supports-color@0.2.0, has-ansi@0.1.0, strip-ansi@0.3.0)
├── bower@1.4.1 (is-root@1.0.0, junk@1.0.1, stringify-object@1.0.1, user-home@1.1.1, chmodr@0.1.0, abbrev@1.0.7, rimraf@2.4.0, archy@1.0.0, opn@1.0.2, bower-logger@0.2.2, bower-endpoint-parser@0.2.2, graceful-fs@3.0.8, lru-cache@2.6.4, lockfile@1.0.1, nopt@3.0.2, retry@0.6.1, tmp@0.0.24, request-progress@0.3.1, q@1.4.1, shell-quote@1.4.3, chalk@1.0.0, which@1.1.1, bower-json@0.4.0, semver@2.3.2, fstream@1.0.7, p-throttler@0.1.1, mkdirp@0.5.0, promptly@0.2.0, fstream-ignore@1.0.2, glob@4.5.3, insight@0.5.3, tar-fs@1.5.1, update-notifier@0.3.2, decompress-zip@0.1.0, request@2.53.0, github@0.2.4, bower-registry-client@0.3.0, cardinal@0.4.4, mout@0.11.0, bower-config@0.6.1, configstore@0.3.2, handlebars@2.0.0, inquirer@0.8.0)
└── google-cdn@0.7.0 (regexp-quote@0.0.0, google-cdn-data@0.1.17, async@0.9.2, debug@1.0.4, semver@2.3.2, cdnjs-cdn-data@0.1.1, bower@1.3.12)
Running "wiredep:app" (wiredep) task

Running "wiredep:test" (wiredep) task

Running "wiredep:sass" (wiredep) task

Done, without errors.


Execution Time (2015-06-19 15:24:26 UTC)
loading tasks   28ms  ▇▇▇▇ 5%
wiredep:app    519ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 86%
wiredep:test    29ms  ▇▇▇▇ 5%
wiredep:sass    29ms  ▇▇▇▇ 5%
Total 607ms
```
I had to `Ctrl+C` and run `grunt serve`. Now since the bootstrap css isn't included, the page looks broken:

![](http://i.imgur.com/cQs53AR.png)

**My environment is:**
Mac OS X 10.9.5
node v0.12.0
npm 2.11.3

**Comment by arthurvr** [comment] 2015-06-19 15:51
@mohislm Chances are high this is a dupe of https://github.com/yeoman/generator-angular/issues/1116. Can you confirm that?

**Comment by mohislm** [comment] 2015-06-19 15:52
Yes.

**Comment by arthurvr** [comment] 2015-06-19 15:55
Well, let's close the issue then :)

**Closed by arthurvr** 2015-06-19 15:55 UTC
