### ISSUE TITLE
Can't generate a new route

### ISSUE THREAD

**Issue by mrmayfield** [yeoman/generator-angular#1154] opened 2015-08-03 19:57 UTC
Here's the error message I receive:

```
$ yo angular:route myroute

fs.js:568
  function strWrapper(err, written) {
                ^
Error: ENOENT, no such file or directory '/Users/leswan/Development/snapcoin/app/scripts/app.js'
    at Error (native)
    at Object.fs.openSync (fs.js:502:18)
    at Object.fs.readFileSync (fs.js:354:15)
    at Object.rewriteFile (/usr/local/lib/node_modules/generator-angular/util.js:50:22)
    at Generator.rewriteAppJs (/usr/local/lib/node_modules/generator-angular/route/index.js:38:16)
    at /usr/local/lib/node_modules/generator-angular/node_modules/yeoman-generator/lib/base.js:341:43
    at /usr/local/lib/node_modules/generator-angular/node_modules/yeoman-generator/node_modules/async/lib/async.js:551:21
    at /usr/local/lib/node_modules/generator-angular/node_modules/yeoman-generator/node_modules/async/lib/async.js:227:13
    at iterate (/usr/local/lib/node_modules/generator-angular/node_modules/yeoman-generator/node_modules/async/lib/async.js:134:13)
    at async.eachSeries (/usr/local/lib/node_modules/generator-angular/node_modules/yeoman-generator/node_modules/async/lib/async.js:150:9)
```

I may reinstall the app but I'd rather not since it takes quite a while for me. Any ideas? Thanks.

**Comment by eddiemonge** [comment] 2015-08-03 20:44
Does that file exist?

**Comment by mrmayfield** [comment] 2015-08-03 23:05
No it doesn't, I have a controllers folder in that directory but no app.js 

Not sure if I should have one, it was a few weeks ago when I fired up the generator so I'm not sure if I changed any defaults and or need to change some path to make this route generation work.

PS: Just took a look and it looks like I renamed 'app' to 'client'. Any ways I can still use the generator to create routes / controllers?

**Comment by eddiemonge** [comment] 2015-08-04 00:20
Not at the moment. I am going to close this since its not a bug but more a duplicate feature request.

**Closed by eddiemonge** 2015-08-04 00:20 UTC

**Comment by mrmayfield** [comment] 2015-08-04 20:22
Not super-duper familiar with Yeoman internals. Can I hack something and change the path? Just from a curiosity point of view, I don't think that's actually a solution I will want to use long term.

**Comment by eddiemonge** [comment] 2015-08-04 20:30
You could fork the project and then change app.js in the code.
