### ISSUE TITLE
Problem getting bootstrap.css to be included using wiredep

### ISSUE THREAD

**Issue by mounte** [yeoman/generator-angular#1116] opened 2015-06-17 11:58 UTC
When I create a project using:
yo angular
no to compass, yes to bootstrap.
running on ubuntu server 14.04
Everything runs through smooth. I can start up the server with grunt serve but I am presented an unstyled page like this:
![image](https://cloud.githubusercontent.com/assets/131137/8206263/2963e24c-14f8-11e5-9b18-e32c89139186.png)

The header of html looks like:

    
    
    
    
    
    
    <link rel="stylesheet" href="styles/main.css">
    

So, no link rel to the bootstrap main css. When I run the grunt build I dont get anything either.
The output of grunt wiredep --verbose --debug is:

    Running "wiredep:app" (wiredep) task
    [D] Task source: /home/danielw/aapp/node_modules/grunt-wiredep/tasks/wiredep.js
    Verifying property wiredep.app exists in config...OK
    Files: app/index.html
    Verifying property wiredep.app.src exists in config...OK
    Options: src=["app/index.html"], ignorePath={}

In the same machine if I start using the webapp generator everything works as expected.
Any idea why it is like this?

**Comment by wavebreakmedia** [comment] 2015-06-17 13:51
I'm having the same issue under windows

**Comment by inaffect-ag** [comment] 2015-06-17 14:16
me too

**Comment by strongwray** [comment] 2015-06-17 15:54
me too,how to deal with this problem? before i used it's ok.

**Comment by RipCurrent** [comment] 2015-06-17 16:48
ditto! but found this a great way of getting to understand yeoman :)

**Comment by joaopedropannain** [comment] 2015-06-17 18:10
It's something wrong with bower.

I put the bootstrap.css on bower components, but grunt remove after few seconds:

 
 <link rel="stylesheet" href="bower_components/bootstrap/dist/css/bootstrap.css" />

I don't know about bower to correct the script, but create a another css before bower:css

 
    <link rel="stylesheet" href="bower_components/bootstrap/dist/css/bootstrap.css" />

**Comment by hpieroni** [comment] 2015-06-18 00:15
I'm having the same problem.

**Comment by masakura** [comment] 2015-06-18 00:16
Me too.

**Comment by nivek91** [comment] 2015-06-18 00:17
+1 same problem, apparently  they removed css from bower.json

  "main": [
    "less/bootstrap.less",
    "dist/js/bootstrap.js"
  ],

**Comment by dspice** [comment] 2015-06-18 07:20
Some temp fixes and causes listed here:
https://github.com/twbs/bootstrap/issues/16663

Some Bootstrap bower.json changes broke wiredep insertions.

**Comment by cvrebert** [comment] 2015-06-18 09:46
See taptapship/wiredep#180 and bower/bower.json-spec/pull/43

**Comment by 47ronin** [comment] 2015-06-18 19:16
Bootstrap v3.3.5 will break and delete the bootstrap.css include. Downgrading to v3.3.4 will fix this!

**Comment by dovy** [comment] 2015-06-22 20:37
Boostrap 3.3.5 is replaced with Boostrap 3.0.0 for me...

**Comment by Frondor** [comment] 2015-06-23 03:10
This worked for me: http://stackoverflow.com/questions/30946498/yeoman-and-bower-not-adding-bootstrap-css-angular-generator

Something is wrong with matching versions

**Comment by eddiemonge** [comment] 2015-06-24 20:09
Uh well this is interesting. Setting the version of Bootstrap to 3.3.4 for now. @stephenplusplus @sindresorhus ideas?

**Comment by budkin76** [comment] 2015-06-27 00:32
+1 This is driving me mad.

**Comment by yijingping** [comment] 2015-06-30 10:06
@eddiemonge thanks. it works for me.

**Comment by shakhrillo** [comment] 2015-06-30 12:50
+1 I did not find the answer and I removed all and wrote my code myself

**Comment by eddiemonge** [comment] 2015-06-30 18:44
Should be fixed in 0.12.0

**Closed by eddiemonge** 2015-06-30 18:44 UTC
Labels: bug, feedback-wanted, pr-welcome

**Comment by harishkumarchellappa** [comment] 2015-07-02 06:44
Changing to 3.3.4 worked...thanks

**Comment by rapasoft** [comment] 2015-07-05 19:59
@eddiemonge yup, it works... but it's a bummer

**Comment by salangar** [comment] 2015-07-29 09:10
Is this issue fixed for Bootstrap 3.3.5? I am using 3.3.5 and unable to include css in dist-index.html. I manually edited bower.json to include the following: "overrides": {
  "bootstrap": {
    "main": [
      "dist/css/bootstrap.css"
       ]
    }

**Comment by rapasoft** [comment] 2015-07-30 08:08
I've just discovered that after setting "minimumResultsForSearch: -1" select2-blur event is not triggered anymore.

**Comment by rotatopoti** [comment] 2015-08-24 22:50
Confirmed. This is a bootstrap issue. Change bootstrap version in bower

**Comment by webskin** [comment] 2015-09-23 14:51
Change to 3.3.4 did the trick

**Comment by javarch** [comment] 2015-09-23 14:56
Ich werde ab  16.09.2015 nicht im B�ro sein. Ich kehre zur�ck am
12.10.2015.
Ich werde Ihre Nachricht nach meiner R�ckkehr beantworten.

Die R�ckmeldung bezieht sich auf ein Mail mit folgendem Thema:
Re: [generator-angular] Problem getting bootstrap.css to be included using
wiredep (#1116)

____________________________________________________________________________________________
Gesendet (c) GRZ/RACON Linz 2015 Agent 'Abwesenheit'


Der Austausch von Nachrichten mit o.a. Absender via e-mail dient
ausschlie�lich Informationszwecken. Rechtsgesch�ftliche Erkl�rungen d�rfen
�ber dieses Medium nicht ausgetauscht werden.

Correspondence with a.m. sender via e-mail is only for information
purposes. This medium is not to be used for the exchange of legally-binding
communications.

**Comment by studiorooster** [comment] 2015-10-09 03:04
Downgrading to 3.3.4 fixed it for me!!

**Comment by javarch** [comment] 2015-10-09 03:14
Ich werde ab  16.09.2015 nicht im B�ro sein. Ich kehre zur�ck am
12.10.2015.
Ich werde Ihre Nachricht nach meiner R�ckkehr beantworten.

Die R�ckmeldung bezieht sich auf ein Mail mit folgendem Thema:
Re: [generator-angular] Problem getting bootstrap.css to be included using
wiredep (#1116)

____________________________________________________________________________________________
Gesendet (c) GRZ/RACON Linz 2015 Agent 'Abwesenheit'

Raiffeisen Software GmbH
Firmenbuchnummer: 86804d, Landesgericht Linz
DVR: 0572934, UID: ATU 36961105

Der Austausch von Nachrichten mit dem oben angef�hrten Absender via E-Mail
dient ausschlie�lich Informationszwecken. Rechtsgesch�ftliche Erkl�rungen
d�rfen �ber dieses Medium nicht ausgetauscht werden.
Correspondence with above mentioned sender via e-mail is only for
information purposes. This medium is not to be used for the exchange of
legally-binding communications.

**Comment by burakhanalkan** [comment] 2015-10-19 16:55
3.3.4 fixed the problem for me, too.
Remove '^' sign also from bower.json, since the latest version is installed.

**Comment by javarch** [comment] 2015-10-19 17:00
Ich werde ab  19.10.2015 nicht im B�ro sein. Ich kehre zur�ck am
23.10.2015.
Ich werde Ihre Nachricht nach meiner R�ckkehr beantworten.

Die R�ckmeldung bezieht sich auf ein Mail mit folgendem Thema:
Re: [generator-angular] Problem getting bootstrap.css to be included using
wiredep (#1116)

____________________________________________________________________________________________
Gesendet (c) GRZ/RACON Linz 2015 Agent 'Abwesenheit'

Raiffeisen Software GmbH
Firmenbuchnummer: 86804d, Landesgericht Linz
DVR: 0572934, UID: ATU 36961105

Der Austausch von Nachrichten mit dem oben angef�hrten Absender via E-Mail
dient ausschlie�lich Informationszwecken. Rechtsgesch�ftliche Erkl�rungen
d�rfen �ber dieses Medium nicht ausgetauscht werden.
Correspondence with above mentioned sender via e-mail is only for
information purposes. This medium is not to be used for the exchange of
legally-binding communications.

**Comment by bengrunfeld** [comment] 2015-10-22 04:47
:+1:  to the bootstrap version fix.

**Comment by Codermar** [comment] 2015-10-27 16:29
I think most of the answers seem to miss the point. The issue is obviously the main property in the bower.json file for bootstrap in this case (and I actually had the same issue with font-awesome 4.4) It seems like they are changing the convention to include the less files in the main instead of the css and that wiredep does not know about it. See https://github.com/taptapship/wiredep/issues/210

**Comment by j-w-miller** [comment] 2015-11-02 22:13
> Codermar commented 6 days ago ...

tweaking bower.json solved it for me.
was
  `"main": [
    "less/bootstrap.less",
    "dist/js/bootstrap.js"
  ]`
modified
 ` "main": [
    "dist/css/bootstrap.css",
    "dist/js/bootstrap.js"
  ],`

**Comment by saqib053** [comment] 2015-11-03 20:29
Do the following in your working directory
bower install bootstrap-css --save

**Comment by WayneRiesterer** [comment] 2015-11-06 12:15
This problem is due to the bower.json file for Bootstrap 3.3.5 as many have mentioned above.

Downgrading to a previous version might work, but then you lose the benefit of the latest version.

Changing the bower.json file in /bower_components/bootstrap may provide a temporary fix, but if you reload your packages, or use `bower install` for an initial setup, then the previous package bower.json file will be replaced and then you're back to square one.

You can use an override in *your project's* bower.json file to redefine an errant or missing property from the *package's* bower.json file.

To do this, open your **project's** bower.json file and put this just after dependencies:

```
  "overrides": {
    "bootstrap": {
      "main": [
        "dist/js/bootstrap.js",
        "dist/css/bootstrap.css",
        "less/bootstrap.less"
      ]
    }
  }
```

You can find more information on wiredep's bower overrides at the following link:

https://www.npmjs.com/package/wiredep#bower-overrides

Enjoy :)

**Comment by katlimruiz** [comment] 2015-11-20 19:12
@WayneRiesterer comment worked for me.

**Comment by mymai91** [comment] 2015-11-21 08:54
In index.html
```
<!-- build:css(.) styles/vendor.css -->
      <link rel="stylesheet" href="../bower_components/bootstrap/dist/css/bootstrap.css" />
<!-- bower:css -->
```

**Comment by sean-madhavan** [comment] 2015-11-24 03:55
@mymai91 that code is removed once you run grunt.

**Comment by kutyel** [comment] 2015-11-25 19:42
I am runing `gulp` and have the same error, tried downgrading bootstrap to 3.3.4 and still happens, plus a weird error `Error in plugin 'run-sequence'
Message:
    An error occured in task 'client:build'.` Any ideas?

**Comment by mymai91** [comment] 2015-11-26 04:02
@sean-madhavan you are right

**Comment by hakimirza** [comment] 2015-12-13 02:38
@WayneRiesterer I'm using Bootstrap 3.3.6 and your solution worked very well, thank you :)

**Comment by fabiopaiva** [comment] 2015-12-30 14:52
the problem persist using gulp, grunt ok

**Comment by ismaproco** [comment] 2016-01-16 18:11
@WayneRiesterer your solution worked for me, this is my bower.json
```javascript
{
  "name": "testapp",
  "private": true,
  "version": "0.1.0",
  "dependencies": {
    "bootstrap": "~3.x.x",
  },
  "overrides": {
    "bootstrap": {
      "main": [
        "dist/js/bootstrap.js",
        "dist/css/bootstrap.css",
        "less/bootstrap.less"
      ]
    }
  }
}
```

**Comment by postalC** [comment] 2016-01-21 12:20
Any work-around for gulp, tried various suggestion and none of them work for gulp.

**Comment by anilsawant** [comment] 2016-02-03 06:57
I did the following selections and it worked for me: 
`? Would you like to use Gulp (experimental) instead of Grunt? (y/N) n`
`? Would you like to use Gulp (experimental) instead of Grunt? No`
`? Would you like to use Sass (with Compass)? (Y/n) n`
`? Would you like to use Sass (with Compass)? No`
`? Would you like to include Bootstrap? (Y/n) y`
`? Would you like to include Bootstrap? Yes`

**Comment by overmedia** [comment] 2016-02-08 01:14
@WayneRiesterer solution worked for me.

**Comment by overmedia** [comment] 2016-02-15 03:49
@WayneRiesterer solution worked for me.
"bootstrap": "^3.2.0" on OS X

**Comment by ariefitriadin** [comment] 2016-02-29 09:01
@WayneRiesterer your solution worked for me, this is my bower.json

{
  "name": "testapp",
  "private": true,
  "version": "0.1.0",
  "dependencies": {
    "bootstrap": "~3.x.x",
  },
  "overrides": {
    "bootstrap": {
      "main": [
        "dist/js/bootstrap.js",
        "dist/css/bootstrap.css",
        "less/bootstrap.less"
      ]
    }
  }
}



yeah this work as well for me

**Comment by jxc876** [comment] 2016-03-01 02:38
reminder to self, downgrade bootstrap... :(

**Comment by khemkaran14** [comment] 2016-03-18 12:21
got the same issue on windows...
just did bower install bootstrap
and then
grunt serve
it worked for me.

**Comment by khemkaran14** [comment] 2016-03-18 12:24
got the same issue on windows...
just did 
`bower install bootstrap`
and then
`grunt serve`
it worked for me.

**Comment by victorazevedo** [comment] 2016-06-01 18:57
I put '<link rel="stylesheet" href="bower_components/bootstrap/dist/css/bootstrap.css">' in the index.html and it´s working now.

**Comment by gouravmakhija18** [comment] 2016-06-14 19:06
I have added **"bootstrap-sass-official": "~3.1.0"**, at top of dependencies, everything work awesome.

e.g.

    "dependencies": {
                "bootstrap-sass-official": "~3.1.0",
                 "jquery": "~2.1.4",

**Comment by eMahtab** [comment] 2016-08-18 10:19
Just switched to bootstrap 3.3.4 and it worked. Oohh ...

**Comment by Murrugarra** [comment] 2016-11-13 20:56
Ohh. Changing to 3.3.4 Did the Trick. Thank you so much.!

**Comment by stefanbaumg** [comment] 2016-12-21 22:34
@WayneRiesterer's solution also works for bootswatch with slight modification:

```json
"overrides": {
    "bootswatch-dist": {
      "main": [
        "js/bootstrap.js",
        "css/bootstrap.css",
        "bootstrap.less"
      ]
    }
  }
```

**Comment by pavlito** [comment] 2017-03-01 12:39
Hi guys, you can still use latest version of bootstrap 3.3.7 .

You need to modify bower.json located inside bootstrap folder.

Need to add key "overrides and specify bootstrap.css location.

 

Here is mine content 
`<pre>
{
    "name": "yb",
    "description": "YourBourse project",
    "main": "index.html",
    "authors": [
        "Pavle Lucic <pavlito1988@gmail.com>"
    ],
    "license": "MIT",
    "homepage": "",
    "private": true,
    "ignore": [
        "**/.*",
        "node_modules",
        "bower_components",
        "app/libs",
        "test",
        "tests"
    ],
    "dependencies": {
        "respond": "^1.4.2",
        "html5shiv": "^3.7.3",
        "modernizr": "^3.3.1",
        "jquery": "^3.1.1",
        "bootstrap": "3.3.7",
        "bootstrap3-ie10-viewport-bug-workaround": "^1.0.0"
    },
    "overrides": {
        "bootstrap": {
            "main": [
                "dist/css/bootstrap.css"
            ]
        }
    }
}
</pre>`

**Comment by jpdavy** [comment] 2017-03-09 21:07
Wiredep works by looking at the bower.json file inside the bower packages file. In this case bower_components/bootstrap/

Open bower_components/bootstrap/bower.json and change:
```
  "main": [
    "less/bootstrap.less",
    "dist/js/bootstrap.js"
  ],
```
to
```
  "main": [
    "less/bootstrap.less",
    "dist/js/bootstrap.js",
    "dist/css/bootstrap.css"
  ],
```
If you want to use the bootstrap theme css as well:
```
  "main": [
    "less/bootstrap.less",
    "dist/js/bootstrap.js",
    "dist/css/bootstrap.css",
    "dist/css/bootstrap-theme.css"
  ],
```
