### ISSUE TITLE
Bootstrap 3.3.5 does not work

### ISSUE THREAD

**Issue by jweigend** [yeoman/generator-angular#1121] opened 2015-06-19 16:02 UTC
I generated a new sample with yo angular. Since today all bootstrap layouts and styles do not work.
I assume there is a problem with bootstrap 3.3.5. When switching back to 3.3.4 in bower properties evertyhing works fine as before.

**Comment by arthurvr** [comment] 2015-06-19 16:04
This is clearly a duplicate of https://github.com/yeoman/generator-angular/issues/1116. Do a quick search before opening an issue ;)

**Closed by arthurvr** 2015-06-19 16:04 UTC

**Comment by jweigend** [comment] 2015-06-20 12:16
Sorry. But if you would make any notice on your main page this would help. I am now aware that this is a bower problem. Anyway, the generated site does not work since it depends on the latest available bootstrap version. I would seriosly think about setting the dependency version fix.
