### ISSUE TITLE
my css files are empty

### ISSUE THREAD

**Issue by tsinat** [yeoman/generator-angular#1241] opened 2015-12-30 07:14 UTC
every thing seems to work right when i run "grunt serve" in my Yoman generated webapp and I see my scss compiled in the .tmp folder, but when I run "grunt build" my css file is available in the dist folder with nothing in it.

I have got those two empty files
      main.d41d8cd9.css
      vendor.d41d8cd9.css

[Gruntfilejs.txt](https://github.com/yeoman/generator-angular/files/74660/Gruntfilejs.txt)

**Comment by sindresorhus** [comment] 2015-12-30 11:59
Duplicate of https://github.com/yeoman/generator-webapp/issues/628. Please don't double-post.

**Closed by sindresorhus** 2015-12-30 11:59 UTC
