### ISSUE TITLE
Paths to fonts does not get updated in styles on build

### ISSUE THREAD

**Issue by filipjohansson** [yeoman/generator-angular#1025] opened 2015-03-05 10:41 UTC
When I do a `grunt build` the paths to my fonts does not get updated. This is what the result looks like in my minified styles.css.
```
@font-face{font-family:Polo;src:url(.tmp/styles/fonts/p22r.eot);src:url(.tmp/styles/fonts/p22r.eot?#iefix) format("embedded-opentype"),url(.tmp/styles/fonts/p22r.woff) format("woff"),url(.tmp/styles/fonts/p22r.ttf) format("truetype");font-weight:400;font-style:normal}
```
I have older projects where this is working but not in my new project.

**Comment by cebor** [comment] 2015-03-05 11:44
Duplicate of: https://github.com/yeoman/generator-angular/issues/1011

**Closed** 2015-03-05 21:04 UTC
Labels: duplicate
