### ISSUE TITLE
Having an issue scaffolding

### ISSUE THREAD

**Issue by justinchristensen66** [yeoman/generator-angular#1157] opened 2015-08-06 02:02 UTC
I am having problems scaffolding the generator.  It never finishes, it gets down to "Running wire:dep test" (wiredep) task, says it is done without errors, gives execution time and then sits there and never returns me to $ so I can run 'grunt serve',  I left it for 2hrs thinking it just needed time but that didn't help.  So I control C out of generator and run grunt serve, the server is spun up but the styles are not injected.  (screenshot attached)
![screen shot 2015-08-05 at 6 54 53 pm](https://cloud.githubusercontent.com/assets/2721110/9102134/d6f7dde2-3ba3-11e5-87b3-7d72cd52807c.png)

here is the terminal output

 ´   `  |° ´ Y `

Out of the box I include Bootstrap and some AngularJS recommended modules.

? Would you like to use Sass (with Compass)? No
? Would you like to include Bootstrap? Yes
? Which modules would you like to include? angular-animate.js, angular-cookies.js, angular-resource.js, angular-route.js, angular-sanitize.js, angular-touch.js
   create app/styles/main.css
   create app/index.html
   create bower.json
   create .bowerrc
   create package.json
   create Gruntfile.js
   create README.md
   invoke   angular:common:/Users/justinchristensen66/.nvm/v0.12.7/lib/node_modules/generator-angular/app/index.js
   create     .editorconfig
   create     .gitattributes
   create     .jshintrc
   create     .yo-rc.json
   create     .gitignore
   create     test/.jshintrc
   create     app/.buildignore
   create     app/.htaccess
   create     app/404.html
   create     app/favicon.ico
   create     app/robots.txt
   create     app/views/main.html
   create     app/images/yeoman.png
   invoke   angular:main:/Users/justinchristensen66/.nvm/v0.12.7/lib/node_modules/generator-angular/app/index.js
   create     app/scripts/app.js
   invoke   angular:controller:/Users/justinchristensen66/.nvm/v0.12.7/lib/node_modules/generator-angular/app/index.js
   create     app/scripts/controllers/main.js
   create     test/spec/controllers/main.js
   invoke   karma:app

I'm all done. Running bower install & npm install for you to install the required dependencies. If this fails, try running the command yourself.

   invoke       angular:route
   invoke           angular:controller:/Users/justinchristensen66/.nvm/v0.12.7/lib/node_modules/generator-angular/route/index.js
   create             app/scripts/controllers/about.js
   create             test/spec/controllers/about.js
   invoke           angular:view:/Users/justinchristensen66/.nvm/v0.12.7/lib/node_modules/generator-angular/route/index.js
   create             app/views/about.html
   create     test/karma.conf.js
 conflict     package.json
? Overwrite package.json? (Ynaxdh) npm WARN package.json mytodo@0.0.0 No license field.
bower cached        git://github.com/twbs/bootstrap.git#3.3.5
bower validate      3.3.5 against git://github.com/twbs/bootstrap.git#^3.2.0
bower cached        git://github.com/angular/bower-angular-animate.git#1.4.3
bower validate      1.4.3 against git://github.com/angular/bower-angular-animate.git#^1.3.0
bower cached        git://github.com/angular/bower-angular-touch.git#1.4.3
bower validate      1.4.3 against git://github.com/angular/bower-angular-touch.git#^1.3.0
bower cached        git://github.com/angular/bower-angular.git#1.4.3
bower validate      1.4.3 against git://github.com/angular/bower-angular.git#^1.3.0
bower cached        git://github.com/angular/bower-angular-resource.git#1.4.3
bower validate      1.4.3 against git://github.com/angular/bower-angular-resource.git#^1.3.0
bower cached        git://github.com/angular/bower-angular-mocks.git#1.4.3
bower validate      1.4.3 against git://github.com/angular/bower-angular-mocks.git#^1.3.0
bower cached        git://github.com/angular/bower-angular-sanitize.git#1.4.3
bower validate      1.4.3 against git://github.com/angular/bower-angular-sanitize.git#^1.3.0
bower cached        git://github.com/angular/bower-angular-route.git#1.4.3
bower validate      1.4.3 against git://github.com/angular/bower-angular-route.git#^1.3.0
bower cached        git://github.com/angular/bower-angular-cookies.git#1.4.3
bower validate      1.4.3 against git://github.com/angular/bower-angular-cookies.git#^1.3.0
bower cached        git://github.com/jquery/jquery.git#2.1.4
bower validate      2.1.4 against git://github.com/jquery/jquery.git#>= 1.9.1
bower install       angular#1.4.3
bower install       bootstrap#3.3.5
bower install       angular-animate#1.4.3
bower install       angular-touch#1.4.3
bower install       angular-resource#1.4.3
bower install       angular-sanitize#1.4.3
bower install       angular-cookies#1.4.3
bower install       angular-mocks#1.4.3
bower install       angular-route#1.4.3
bower install       jquery#2.1.4
\
angular#1.4.3 bower_components/angular

bootstrap#3.3.5 bower_components/bootstrap
└── jquery#2.1.4

angular-animate#1.4.3 bower_components/angular-animate
└── angular#1.4.3

angular-touch#1.4.3 bower_components/angular-touch
└── angular#1.4.3

angular-resource#1.4.3 bower_components/angular-resource
└── angular#1.4.3

angular-sanitize#1.4.3 bower_components/angular-sanitize
└── angular#1.4.3

angular-cookies#1.4.3 bower_components/angular-cookies
└── angular#1.4.3

angular-mocks#1.4.3 bower_components/angular-mocks
└── angular#1.4.3

angular-route#1.4.3 bower_components/angular-route
└── angular#1.4.3

jquery#2.1.4 bower_components/jquery

> jpegtran-bin@3.0.4 postinstall /Users/justinchristensen66/Sites/mytodo/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin
> node lib/install.js

  ✔ jpegtran pre-build test passed successfully

> gifsicle@3.0.1 postinstall /Users/justinchristensen66/Sites/mytodo/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle
> node lib/install.js

  ✔ gifsicle pre-build test passed successfully

> optipng-bin@3.0.2 postinstall /Users/justinchristensen66/Sites/mytodo/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin
> node lib/install.js

  ✔ optipng pre-build test passed successfully
grunt-contrib-clean@0.6.0 node_modules/grunt-contrib-clean
└── rimraf@2.2.8

grunt-concurrent@1.0.1 node_modules/grunt-concurrent
├── pad-stdio@1.0.0 (lpad@1.0.0)
└── async@0.9.2

grunt-contrib-copy@0.7.0 node_modules/grunt-contrib-copy
└── chalk@0.5.1 (ansi-styles@1.1.0, escape-string-regexp@1.0.3, supports-color@0.2.0, strip-ansi@0.3.0, has-ansi@0.1.0)

grunt-filerev@2.3.1 node_modules/grunt-filerev
├── each-async@0.1.3
├── convert-source-map@1.1.1
└── chalk@1.1.0 (escape-string-regexp@1.0.3, supports-color@2.0.0, ansi-styles@2.1.0, strip-ansi@3.0.0, has-ansi@2.0.0)

jshint-stylish@1.0.2 node_modules/jshint-stylish
├── log-symbols@1.0.2
├── text-table@0.2.0
├── string-length@1.0.1 (strip-ansi@3.0.0)
└── chalk@1.1.0 (escape-string-regexp@1.0.3, supports-color@2.0.0, ansi-styles@2.1.0, strip-ansi@3.0.0, has-ansi@2.0.0)

time-grunt@1.2.1 node_modules/time-grunt
├── date-time@1.0.0
├── figures@1.3.5
├── number-is-nan@1.0.0
├── text-table@0.2.0
├── hooker@0.2.3
├── chalk@1.1.0 (escape-string-regexp@1.0.3, supports-color@2.0.0, ansi-styles@2.1.0, has-ansi@2.0.0, strip-ansi@3.0.0)
└── pretty-ms@1.4.0 (parse-ms@1.0.0, get-stdin@4.0.1, is-finite@1.0.1, plur@1.0.0, meow@3.3.0)

grunt-newer@1.1.1 node_modules/grunt-newer
├── rimraf@2.2.8
└── async@0.9.0

grunt-contrib-concat@0.5.1 node_modules/grunt-contrib-concat
├── chalk@0.5.1 (ansi-styles@1.1.0, escape-string-regexp@1.0.3, supports-color@0.2.0, has-ansi@0.1.0, strip-ansi@0.3.0)
└── source-map@0.3.0 (amdefine@1.0.0)

load-grunt-tasks@3.2.0 node_modules/load-grunt-tasks
├── multimatch@2.0.0 (array-differ@1.0.0, array-union@1.0.1, minimatch@2.0.10)
└── findup-sync@0.2.1 (glob@4.3.5)

grunt-contrib-watch@0.6.1 node_modules/grunt-contrib-watch
├── async@0.2.10
├── tiny-lr-fork@0.0.5 (debug@0.7.4, faye-websocket@0.4.4, noptify@0.0.3, qs@0.5.6)
├── gaze@0.5.1 (globule@0.1.0)
└── lodash@2.4.2

grunt-usemin@3.0.0 node_modules/grunt-usemin
├── debug@2.1.3 (ms@0.7.0)
├── chalk@0.5.1 (ansi-styles@1.1.0, escape-string-regexp@1.0.3, supports-color@0.2.0, strip-ansi@0.3.0, has-ansi@0.1.0)
└── lodash@2.4.2

grunt-contrib-connect@0.9.0 node_modules/grunt-contrib-connect
├── opn@1.0.2
├── connect-livereload@0.5.3
├── async@0.9.2
├── portscanner@1.0.0 (async@0.1.15)
└── connect@2.30.2 (cookie@0.1.3, bytes@2.1.0, utils-merge@1.0.0, cookie-signature@1.0.6, fresh@0.3.0, pause@0.1.0, response-time@2.3.1, vhost@3.0.1, content-type@1.0.1, on-headers@1.0.0, basic-auth-connect@1.0.0, parseurl@1.3.0, cookie-parser@1.3.5, depd@1.0.1, http-errors@1.3.1, connect-timeout@1.6.2, method-override@2.3.5, serve-favicon@2.3.0, qs@4.0.0, debug@2.2.0, finalhandler@0.4.0, morgan@1.6.1, csurf@1.8.3, express-session@1.11.3, serve-static@1.10.0, type-is@1.6.6, multiparty@3.3.2, compression@1.5.2, errorhandler@1.4.2, body-parser@1.13.3, serve-index@1.7.2)

grunt-contrib-htmlmin@0.4.0 node_modules/grunt-contrib-htmlmin
├── chalk@0.5.1 (ansi-styles@1.1.0, escape-string-regexp@1.0.3, supports-color@0.2.0, strip-ansi@0.3.0, has-ansi@0.1.0)
├── pretty-bytes@1.0.4 (get-stdin@4.0.1, meow@3.3.0)
└── html-minifier@0.7.2 (relateurl@0.2.6, change-case@2.3.0, concat-stream@1.4.10, cli@0.6.6, clean-css@3.1.9, uglify-js@2.4.24)

grunt@0.4.5 node_modules/grunt
├── dateformat@1.0.2-1.2.3
├── which@1.0.9
├── eventemitter2@0.4.14
├── getobject@0.1.0
├── rimraf@2.2.8
├── colors@0.6.2
├── async@0.1.22
├── grunt-legacy-util@0.2.0
├── hooker@0.2.3
├── exit@0.1.2
├── nopt@1.0.10 (abbrev@1.0.7)
├── minimatch@0.2.14 (sigmund@1.0.1, lru-cache@2.6.5)
├── glob@3.1.21 (inherits@1.0.0, graceful-fs@1.2.3)
├── lodash@0.9.2
├── coffee-script@1.3.3
├── underscore.string@2.2.1
├── iconv-lite@0.2.11
├── findup-sync@0.1.3 (glob@3.2.11, lodash@2.4.2)
├── grunt-legacy-log@0.1.2 (grunt-legacy-log-utils@0.1.1, underscore.string@2.3.3, lodash@2.4.2)
└── js-yaml@2.0.5 (argparse@0.1.16, esprima@1.0.4)

grunt-contrib-cssmin@0.12.3 node_modules/grunt-contrib-cssmin
├── chalk@1.1.0 (escape-string-regexp@1.0.3, supports-color@2.0.0, ansi-styles@2.1.0, has-ansi@2.0.0, strip-ansi@3.0.0)
├── clean-css@3.3.7 (commander@2.8.1, source-map@0.4.4)
└── maxmin@1.1.0 (figures@1.3.5, pretty-bytes@1.0.4, gzip-size@1.0.0)

grunt-contrib-uglify@0.7.0 node_modules/grunt-contrib-uglify
├── uri-path@0.0.2
├── chalk@0.5.1 (ansi-styles@1.1.0, escape-string-regexp@1.0.3, supports-color@0.2.0, has-ansi@0.1.0, strip-ansi@0.3.0)
├── lodash@2.4.2
├── uglify-js@2.4.24 (uglify-to-browserify@1.0.2, async@0.2.10, yargs@3.5.4, source-map@0.1.34)
└── maxmin@1.1.0 (figures@1.3.5, chalk@1.1.0, pretty-bytes@1.0.4, gzip-size@1.0.0)

grunt-wiredep@2.0.0 node_modules/grunt-wiredep
└── wiredep@2.2.2 (propprop@0.3.0, minimist@1.1.2, chalk@0.5.1, through2@0.6.5, glob@4.5.3, lodash@2.4.2, bower-config@0.5.2)

grunt-ng-annotate@0.9.2 node_modules/grunt-ng-annotate
├── lodash@2.4.2
└── ng-annotate@0.15.4 (tryor@0.1.2, simple-fmt@0.1.0, alter@0.2.0, simple-is@0.2.0, stringset@0.2.1, stringmap@0.2.2, stable@0.1.5, convert-source-map@0.4.1, ordered-ast-traverse@1.1.1, optimist@0.6.1, source-map@0.1.43, acorn@0.11.0)

grunt-svgmin@2.0.1 node_modules/grunt-svgmin
├── log-symbols@1.0.2
├── each-async@1.1.1 (set-immediate-shim@1.0.1, onetime@1.0.0)
├── chalk@1.1.0 (escape-string-regexp@1.0.3, supports-color@2.0.0, ansi-styles@2.1.0, strip-ansi@3.0.0, has-ansi@2.0.0)
├── pretty-bytes@1.0.4 (get-stdin@4.0.1, meow@3.3.0)
└── svgo@0.5.5 (whet.extend@0.9.9, colors@1.1.2, mkdirp@0.5.1, coa@1.0.1, sax@1.1.1, js-yaml@3.3.1)

grunt-contrib-jshint@0.11.2 node_modules/grunt-contrib-jshint
├── hooker@0.2.3
└── jshint@2.8.0 (strip-json-comments@1.0.4, exit@0.1.2, console-browserify@1.1.0, shelljs@0.3.0, minimatch@2.0.10, cli@0.6.6, htmlparser2@3.8.3, lodash@3.7.0)

grunt-autoprefixer@2.2.0 node_modules/grunt-autoprefixer
├── diff@1.2.2
├── chalk@0.5.1 (ansi-styles@1.1.0, escape-string-regexp@1.0.3, supports-color@0.2.0, has-ansi@0.1.0, strip-ansi@0.3.0)
└── autoprefixer-core@5.2.1 (num2fraction@1.1.0, browserslist@0.4.0, postcss@4.1.16, caniuse-db@1.0.30000254)

grunt-google-cdn@0.4.3 node_modules/grunt-google-cdn
├── chalk@0.5.1 (ansi-styles@1.1.0, escape-string-regexp@1.0.3, supports-color@0.2.0, has-ansi@0.1.0, strip-ansi@0.3.0)
├── bower@1.4.1 (is-root@1.0.0, junk@1.0.2, stringify-object@1.0.1, user-home@1.1.1, chmodr@0.1.0, abbrev@1.0.7, archy@1.0.0, opn@1.0.2, bower-logger@0.2.2, bower-endpoint-parser@0.2.2, graceful-fs@3.0.8, lockfile@1.0.1, lru-cache@2.6.5, nopt@3.0.3, retry@0.6.1, tmp@0.0.24, request-progress@0.3.1, q@1.4.1, chalk@1.1.0, shell-quote@1.4.3, which@1.1.1, bower-json@0.4.0, semver@2.3.2, fstream@1.0.7, p-throttler@0.1.1, promptly@0.2.0, mkdirp@0.5.0, glob@4.5.3, fstream-ignore@1.0.2, insight@0.5.3, tar-fs@1.8.1, rimraf@2.4.2, decompress-zip@0.1.0, update-notifier@0.3.2, request@2.53.0, bower-registry-client@0.3.0, github@0.2.4, cardinal@0.4.4, mout@0.11.0, bower-config@0.6.1, configstore@0.3.2, handlebars@2.0.0, inquirer@0.8.0)
└── google-cdn@0.7.0 (regexp-quote@0.0.0, google-cdn-data@0.1.17, async@0.9.2, debug@1.0.4, semver@2.3.2, cdnjs-cdn-data@0.1.1, bower@1.3.12)

grunt-contrib-imagemin@0.9.4 node_modules/grunt-contrib-imagemin
├── gulp-rename@1.2.2
├── async@0.9.2
├── chalk@1.1.0 (escape-string-regexp@1.0.3, supports-color@2.0.0, ansi-styles@2.1.0, strip-ansi@3.0.0, has-ansi@2.0.0)
├── pretty-bytes@1.0.4 (get-stdin@4.0.1, meow@3.3.0)
└── imagemin@3.2.0 (get-stdin@4.0.1, path-exists@1.0.0, optional@0.1.3, buffer-to-vinyl@1.0.0, through2@0.6.5, meow@3.3.0, concat-stream@1.5.0, stream-combiner2@1.0.2, vinyl-fs@1.0.0, imagemin-jpegtran@4.3.0, imagemin-svgo@4.1.2, imagemin-gifsicle@4.2.0, imagemin-optipng@4.3.0)
Running "wiredep:app" (wiredep) task

Running "wiredep:test" (wiredep) task

Done, without errors.

Execution Time (2015-08-05 23:13:11 UTC)
loading tasks  48ms  ▇ 2%
wiredep:app    2.4s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 97%
Total 2.4s

**Comment by justinchristensen66** [comment] 2015-08-06 20:50
I using Yeoman version 1.4.7 instead of 1.4.6, bower and grunt both match the versions that is required.

**Comment by paulJordaan** [comment] 2015-08-06 21:47
Had the same problem today. Check out the discussion over here #1116

**Comment by eddiemonge** [comment] 2015-08-06 22:16
> ? Overwrite package.json? (Ynaxdh)

Duplicate of #1092

**Closed by eddiemonge** 2015-08-06 22:16 UTC

**Comment by justinchristensen66** [comment] 2015-08-08 08:02
Thanks paulJordaan
