### ISSUE TITLE
Bootstrap CSS path missing unless one uses Sass / Compass

### ISSUE THREAD

**Issue by JohnLockwood** [yeoman/generator-angular#1128] opened 2015-06-28 02:12 UTC
Using the generator on a fairly clean Ubuntu box using Yo, without Compass installed, and answer no to the "Would you like to use Sass with Compass" question.  (I.e., pretty much follow the Yeoman codelab Yeoman tutorial).  In this case bootstrap.css is not included in the index.html file.  Installing Compass / Sass and doing it that way is a workaround.  Seems to be true for the last couple of versions, since I backed up to 0.4.0 to try to fix it before trying Sass.

**Comment by hanskoff** [comment] 2015-06-28 07:52
+1

**Comment by houmanka** [comment] 2015-06-29 05:29
+1

**Comment by petit-prince** [comment] 2015-06-29 14:41
+1

**Comment by shakhrillo** [comment] 2015-06-29 17:38
+1

**Comment by eddiemonge** [comment] 2015-06-29 19:06
duplicate of #1116

**Closed by eddiemonge** 2015-06-29 19:06 UTC

**Comment by kapposds** [comment] 2016-11-08 11:25
{
  "name": "test-project",
  "version": "0.0.0",
  "dependencies": {
    "angular": "^1.4.0",
    "bootstrap": "3.3.4",
    "angular-animate": "^1.4.0",
    "angular-aria": "^1.4.0",
    "angular-cookies": "^1.4.0",
    "angular-messages": "^1.4.0",
    "angular-resource": "^1.4.0",
    "angular-route": "^1.4.0",
    "angular-sanitize": "^1.4.0",
    "angular-touch": "^1.4.0"
  },
    "overrides": {
    "bootstrap": {
      "main": [
        "dist/js/bootstrap.js",
        "dist/css/bootstrap.css",
        "less/bootstrap.less"
      ]
    }
  },
  "devDependencies": {
    "angular-mocks": "^1.4.0"
  },
  "appPath": "app",
  "moduleName": "testProjectApp"
}

this is my bower.json file, and I still have the same problem. No css, no bootstrap.
