### ISSUE TITLE
It appears that Bootstrap (CSS) is not working

### ISSUE THREAD

**Issue by briviere** [yeoman/generator-angular#1152] opened 2015-07-30 01:04 UTC
For some reason the CSS is not working.  I guess it can't find the CSS generated.

**Comment by calidion** [comment] 2015-07-30 05:18
https://github.com/twbs/bootstrap/issues/16663

https://github.com/bower/bower.json-spec/pull/43

https://github.com/bower/bower.json-spec/issues/47


Hope will be fixed asap.

**Comment by cvrebert** [comment] 2015-07-30 08:40
> Hope will be fixed asap.

Given Bower's low activity level, I wouldn't count on that.

**Comment by cvrebert** [comment] 2015-07-30 09:59
Duplicate of #1116?

**Comment by arthurvr** [comment] 2015-07-30 10:03
Yep, seems like a dupe.

**Closed by arthurvr** 2015-07-30 10:03 UTC
