### ISSUE TITLE
Issues when working with Angular routes and refreshing the page

### ISSUE THREAD

**Issue by ericmdantas** [yeoman/generator-angular#966] opened 2015-01-05 14:42 UTC
**Problem:**

When working with Angular and its routes, if you reload the page in, let's say, localhost:9000/products, the response will be a 404. Because the server (connect) doesn't recognize the ```/products``` route.

The same will happen for ```/users/1```. And so on.

In these two cases, I'd have in my client routes, something along the lines:

```javascript
.when('/products', {..., templateUrl: 'views/products.html', ...})
.when('/users/:id', {..., templateUrl: 'views/users.html', ...})
.otherwise({redirectTo: '/'})
```

And, as said before, when reloading the page in any route that's not the root, will cause the 404 error.

**Solution:**

It turns out grunt's connect task was updated to handle [this kind of situation](https://github.com/gruntjs/grunt-contrib-connect/commit/a6fb4531d19c77fbca3b670fa8444ea3143d387d). It's available in the version 0.9.0.

Anyway, I had to do the following to get it to work (all modifications inside the main gruntfile.js):

- create a function to always send the index.html:

```javascript
   var _sendIndex = function(req, res, next)
						{
							var fs = require('fs');
							
							fs.readFile('./app/index.html', function(error, info)
							{
								res.setHeader('Content-Type', 'text/html');
								res.end(info);
							});
						};
``` 

- create an array of routes that I'll send the index.html file, so it won't 404:

```javascript
var _on404 = [];
  
_on404.push(['/products', _sendIndex]);
_on404.push(['/users/', _sendIndex]); // notice the trailing slash, it will map to any id
```

- edit the middleware property inside the gruntfile > connect > options > middleware:

```javascript
var _middlewares = [];
			
_middlewares.push(connect.static('.tmp'));
_middlewares.push(connect().use('/bower_components', connect.static('./bower_components')));
_middlewares.push(connect.static(appConfig.app));
			
_on404.forEach(function(array)
			  {
				_middlewares.unshift(array);
			  });
			
return _middlewares;
```

- edit my index.html file inside app > index.html, so it'll respect the root of my app:

```html
<base href="/" />
```

And there you go. Now you can refresh the page without getting the annoying 404 all the time.

I think this should be either documented or be part of the tasks somehow, because it is pretty annoying to fix.

**Comment by eddiemonge** [comment] 2015-01-05 21:44
This is pretty much a duplicate of https://github.com/yeoman/generator-angular/issues/433 and the efforts there.

**Closed by eddiemonge** 2015-01-05 21:44 UTC
