### ISSUE TITLE
Feature-based organization commands

### ISSUE THREAD

**Issue by adamsmithxplusz** [yeoman/generator-angular#986] opened 2015-01-22 23:38 UTC
Currently `yo angular:route myroute`, creates files under:

`app/scripts/controllers/myroute.js`.

Could we add a configuration so that it creates files in a 'feature-based' structure? not sure how the commands would work but it would be super useful for larger projects

**Comment by eddiemonge** [comment] 2015-01-26 19:50
Yes it has been brought up, discussed and in progress. this is a duplicate of many issues though.

**Closed by eddiemonge** 2015-01-26 19:50 UTC
