### ISSUE TITLE
Bootstrap glyphicons omitted for CSS-only builds

### ISSUE THREAD

**Issue by brian428** [yeoman/generator-angular#1126] opened 2015-06-25 19:59 UTC
If standard CSS is chosen for the build, the Bootstrap glyphicons (from bower_components/bootstrap/dist/fonts) are not included during a build.

I see that _build.js has this conditional on line 92:
```
<% if (props.ui.key === 'bootstrap' && props.cssPreprocessor.extension === 'styl') { -%>
  return gulp.src($.mainBowerFiles().concat('bower_components/bootstrap-stylus/fonts/*'))
<% } else { -%>
  return gulp.src($.mainBowerFiles())
<% } -%>
```

I'm wondering if that just needs to be something like this?
```
<% if (props.ui.key === 'bootstrap') { -%>
  return gulp.src($.mainBowerFiles().concat('bower_components/bootstrap*/**/fonts/*'))
<% } else { -%>
  return gulp.src($.mainBowerFiles())
<% } -%>
```

Either that, or a separate `else if` to explicitly handle bootstrap+css mode?

**Comment by eddiemonge** [comment] 2015-06-25 21:27
What is `_build.js`? This is probably a duplicate of https://github.com/yeoman/generator-angular/issues/1116

**Closed by eddiemonge** 2015-06-25 21:27 UTC

**Comment by brian428** [comment] 2015-06-25 23:08
Oops, sorry! I had meant to open this issue on the generator-gulp-angular project! Apologies.
