### ISSUE TITLE
Bug using 'yo angular'

### ISSUE THREAD

**Issue by murilolobato** [yeoman/generator-angular#1071] opened 2015-04-30 14:53 UTC
If I follow the instructions at readme.md, after I execute 'yo angular' I can see that a conflict is happening with package.json, and the terminal ask's if I want to overwrite the file or not. If I dont press any key the process continues, but after the message "Done, without errors." i'm not sent back to bash, and if I hit any key, the overwrite message appears again.

**Comment by CaptSaltyJack** [comment] 2015-05-02 18:09
+1

**Comment by TheWrongAlice** [comment] 2015-05-05 12:41
same here

**Comment by mogupta** [comment] 2015-05-05 19:46
+1

**Comment by arthurvr** [comment] 2015-05-06 19:35
> If I follow the instructions at readme.md, after I execute 'yo angular' I can see that a conflict is happening with package.json, and the terminal ask's if I want to overwrite the file or not.

That's generally because the package.json file already exists where you're trying to generate it. Are you in a totally empty directory?

**Comment by CaptSaltyJack** [comment] 2015-05-06 19:36
Absolutely in a fresh directory. I think perhaps the yeoman generator is creating package.json, then trying to create it a second time.

**Comment by mogupta** [comment] 2015-05-06 19:42
Yes , in a fresh directory.

Note : this is happening only on windows 8.  I installed nodejs using the
node installer.

**Comment by CaptSaltyJack** [comment] 2015-05-06 19:43
Nope, happening on Mac OS too. :)

**Comment by TheWrongAlice** [comment] 2015-05-06 19:54
Confirmed, I have this issue on Mac

**Comment by vladzzag** [comment] 2015-05-07 20:26
I have the same issue on Ubuntu.

**Comment by klode** [comment] 2015-05-09 14:43
I have the same issue, on Mac

It seams to be related to the installation of karma packages which rewrites the package.json adding devDependencies to the karma packages

I ran the generator twice, once answering Yes and once answering No to "Overwrite package.json?"
Here are the differences among the two apps 

The rewritten package.json has "grunt-karma", "karma-jasmine", 
```
$ diff norewrite/package.json sandbox/package.json 
2c2
<   "name": "norewrite",
---
>   "name": "sandbox",
22a23
>     "grunt-karma": "*",
28a30,31
>     "karma-jasmine": "*",
>     "karma-phantomjs-launcher": "*",
33a37,39
>   },
>   "scripts": {
>     "test": "grunt test"
35c41
< }
---
> }
```

here are the corresponding node_modules/ folders

```
$ ls -gG sandbox/node_modules/
total 0
drwxr-xr-x  11 staff  374 May  9 10:05 grunt
drwxr-xr-x   8 staff  272 May  9 10:05 grunt-autoprefixer
drwxr-xr-x   6 staff  204 May  9 10:05 grunt-concurrent
drwxr-xr-x   7 staff  238 May  9 10:05 grunt-contrib-clean
drwxr-xr-x   6 staff  204 May  9 10:05 grunt-contrib-compass
drwxr-xr-x   6 staff  204 May  9 10:05 grunt-contrib-concat
drwxr-xr-x   7 staff  238 May  9 10:05 grunt-contrib-connect
drwxr-xr-x   7 staff  238 May  9 10:05 grunt-contrib-copy
drwxr-xr-x   7 staff  238 May  9 10:05 grunt-contrib-cssmin
drwxr-xr-x   6 staff  204 May  9 10:05 grunt-contrib-htmlmin
drwxr-xr-x   7 staff  238 May  9 10:05 grunt-contrib-imagemin
drwxr-xr-x   7 staff  238 May  9 10:05 grunt-contrib-jshint
drwxr-xr-x   7 staff  238 May  9 10:05 grunt-contrib-uglify
drwxr-xr-x   7 staff  238 May  9 10:05 grunt-contrib-watch
drwxr-xr-x   6 staff  204 May  9 10:05 grunt-filerev
drwxr-xr-x   6 staff  204 May  9 10:05 grunt-google-cdn
drwxr-xr-x  17 staff  578 May  9 10:07 grunt-karma        <------
drwxr-xr-x  14 staff  476 May  9 10:05 grunt-newer
drwxr-xr-x   6 staff  204 May  9 10:05 grunt-ng-annotate
drwxr-xr-x   7 staff  238 May  9 10:05 grunt-svgmin
drwxr-xr-x   7 staff  238 May  9 10:05 grunt-usemin
drwxr-xr-x   9 staff  306 May  9 10:05 grunt-wiredep
drwxr-xr-x  15 staff  510 May  9 10:07 jasmine-core
drwxr-xr-x   8 staff  272 May  9 10:05 jshint-stylish
drwxr-xr-x  16 staff  544 May  9 10:07 karma                 <---------
drwxr-xr-x   7 staff  238 May  9 10:07 karma-jasmine        <----------
drwxr-xr-x   6 staff  204 May  9 10:07 karma-phantomjs-launcher      <----------
drwxr-xr-x   6 staff  204 May  9 10:05 load-grunt-tasks
drwxr-xr-x   7 staff  238 May  9 10:05 time-grunt

$ ls -gG  norewrite/node_modules/
total 0
drwxr-xr-x  11 staff  374 May  9 10:11 grunt
drwxr-xr-x   8 staff  272 May  9 10:11 grunt-autoprefixer
drwxr-xr-x   6 staff  204 May  9 10:11 grunt-concurrent
drwxr-xr-x   7 staff  238 May  9 10:11 grunt-contrib-clean
drwxr-xr-x   6 staff  204 May  9 10:11 grunt-contrib-compass
drwxr-xr-x   6 staff  204 May  9 10:11 grunt-contrib-concat
drwxr-xr-x   7 staff  238 May  9 10:11 grunt-contrib-connect
drwxr-xr-x   7 staff  238 May  9 10:11 grunt-contrib-copy
drwxr-xr-x   7 staff  238 May  9 10:11 grunt-contrib-cssmin
drwxr-xr-x   6 staff  204 May  9 10:11 grunt-contrib-htmlmin
drwxr-xr-x   7 staff  238 May  9 10:11 grunt-contrib-imagemin
drwxr-xr-x   7 staff  238 May  9 10:11 grunt-contrib-jshint
drwxr-xr-x   7 staff  238 May  9 10:11 grunt-contrib-uglify
drwxr-xr-x   7 staff  238 May  9 10:11 grunt-contrib-watch
drwxr-xr-x   6 staff  204 May  9 10:11 grunt-filerev
drwxr-xr-x   6 staff  204 May  9 10:11 grunt-google-cdn
drwxr-xr-x  14 staff  476 May  9 10:11 grunt-newer
drwxr-xr-x   6 staff  204 May  9 10:11 grunt-ng-annotate
drwxr-xr-x   7 staff  238 May  9 10:11 grunt-svgmin
drwxr-xr-x   7 staff  238 May  9 10:11 grunt-usemin
drwxr-xr-x   9 staff  306 May  9 10:11 grunt-wiredep
drwxr-xr-x   8 staff  272 May  9 10:11 jshint-stylish
drwxr-xr-x   6 staff  204 May  9 10:11 load-grunt-tasks
drwxr-xr-x   7 staff  238 May  9 10:11 time-grunt```

```

**Comment by TheWrongAlice** [comment] 2015-05-14 21:54
My "solution" to this problem was to install an earlier version of the generator (0.7.1) which worked nicely for me.

**Comment by murilolobato** [comment] 2015-05-15 00:35
What I need to do to install a earlier version?

**Comment by TheWrongAlice** [comment] 2015-05-15 07:50
@murilolobato 

First uninstall your current version:
`npm uninstall generator-angular`

Then install specific version like so:
`npm install generator-angular@0.7.1`

**Comment by h-arora** [comment] 2015-05-18 17:03
I am also getting the same issue on Mac

**Comment by zishanj** [comment] 2015-05-22 05:13
same issue on Ubuntu... But in addition I am also receiving following message:

    npm WARN optional dep failed, continuing imagemin-gifsicle@4.1.0
    npm WARN optional dep failed, continuing imagemin-jpegtran@4.1.0
    npm WARN optional dep failed, continuing imagemin-optipng@4.2.0

and at the end, following error message:

    events.js:72
        throw er; // Unhandled 'error' event
              ^
    Error: spawn ENOENT
       at errnoException (child_process.js:1011:11)
       at Process.ChildProcess._handle.onexit (child_process.js:802:34)

**Comment by wuethrich44** [comment] 2015-05-29 14:06
Same issue on a windows 8 machine...

**Comment by arthurvr** [comment] 2015-05-29 15:23
I was able to confirm this issue. Thanks everybody. Marking as a bug. Hopefully somebody will have to time to dig into this issue quick.

**Comment by gadieichhorn** [comment] 2015-06-06 18:52
same issue with 0.11.1, 0.11.0 and 0.10.0
installed version 0.8.0 then had to do bower install and npm install (some errors in generator)

grunt serve is working now

**Comment by twrk** [comment] 2015-06-12 01:46
+1

**Comment by murilolobato** [comment] 2015-06-14 22:38
The question is: How to use this generator with this problem? Just press enter until it end? Or the generator is abandoned?

**Comment by arthurvr** [comment] 2015-06-15 05:07
@murilolobato We will hopefully get to fixing this soon. Of course a PR to fix this would be welcome too :) You can always downgrade your generator-angular version and that should work fine.

**Comment by murilolobato** [comment] 2015-06-15 17:58
Unfortunately I've tried, but with no success fix this problem :(

**Comment by arthurvr** [comment] 2015-06-15 18:00
This is a quite critical bug so anyone looking here, we should really try to prioritise it. Maybe @eddiemonge has an idea of the cause?

**Comment by WSzP** [comment] 2015-06-17 21:51
+1 I can confirm that npm install generator-angular@0.7.1 works, but any newer version fails, tested on MacOS & Win 8.1
Everything fresh install, latest version. (Node, npm, bower, grunt, yo, etc)

**Comment by mastef** [comment] 2015-06-18 11:57
:+1:
angularfire generator also affected

**Comment by reinaldo122** [comment] 2015-06-23 16:36
Hi, Same here. Using Linux Mint 17.1.
Latest version of Node, bower, grunt, yo, generator-angular.
My solution was to:
`yo angular AppName`
when package.json conflicts, press Enter
When finished installation, after all the errors, do `npm install`
That works for me, it's not the best solution, but it's a workaround.

**Comment by MartyPye** [comment] 2015-06-23 17:54
Didn't work for me

**Comment by eddiemonge** [comment] 2015-06-24 20:11
Probably has to do with this not being updated to the latest yeoman-generator. Need to do that soon.

**Comment by rezpe** [comment] 2015-06-26 13:48
I have the same issue and using the latest generator:0.11.1

**Comment by IOAyman** [comment] 2015-07-03 03:04
Same issue here.

```
$ yo --version
1.4.7
```

**Comment by BahramN** [comment] 2015-07-06 19:50
same here on ubuntu

**Comment by zac1st1k** [comment] 2015-07-21 11:12
same here

**Comment by zac1st1k** [comment] 2015-07-21 11:12
same here on mac

**Comment by JulienItard** [comment] 2015-07-22 19:32
same here Linux Mint 17.2

**Comment by arthurvr** [comment] 2015-07-22 19:33
We already confirmed this issue, no reason for "same here" or "+1" comments ;)

**Comment by JulienItard** [comment] 2015-07-22 20:12
Updating generator-karma fixed the error on my machine

**Comment by arthurvr** [comment] 2015-07-22 20:16
@JulienItard Oh, that would be awesome news. Can somebody else try the following command and then try if it's fixed? 

```
$ npm i -g generator-karma
```

**Comment by Nonymus** [comment] 2015-07-22 20:35
Nope, not really.You still get

    conflict     package.json
    ? Overwrite package.json?

which quickly bounces off the screen due to bower output kicking in. Only if you hit Enter at some point npm starts to install. The result does work though. No errors from grunt.

Tested with yo@1.4.7, generator-angular@0.12.1, generator-karma@1.0.0 on ubuntu.

**Comment by JulienItard** [comment] 2015-07-22 20:41
Yes, i have to overwrite package.json at the end but now i have'nt  the error

events.js:72
    throw er; // Unhandled 'error' event
          ^
Error: spawn ENOENT
   at errnoException (child_process.js:1011:11)
   at Process.ChildProcess._handle.onexit (child_process.js:802:34)

**Comment by jlsuarezs** [comment] 2015-07-31 07:49
Any news about this issue? I'm having the same problem right now...:-(

**Comment by gilvaju** [comment] 2015-07-31 21:20
Same issue here! Osx Yosemite

**Comment by eddiemonge** [comment] 2015-07-31 21:21
Closing since it doesnt add anything and I know the problem is https://github.com/yeoman/generator-angular/issues/1092

**Closed by eddiemonge** 2015-07-31 21:21 UTC
Labels: bug

**Comment by hackjustu** [comment] 2016-04-15 23:52
+1

**Comment by zivanovicb** [comment] 2016-04-23 23:02
+1

**Comment by zniszcz** [comment] 2016-04-25 13:11
+1

**Comment by 1moere1** [comment] 2016-04-27 21:38
+1

**Comment by nsdelgadov** [comment] 2016-04-29 12:49
Hello, I don't know if this is well, but I did:

1) npm install grunt-karma --save-dev 
2) npm install karma-phantomjs-launcher --save-dev

[Source]( https://recalll.co/app/?q=node.js%20-%20Warning:%20Task%20%22karma%22%20not%20found%20when%20running%20grunt%20test)

PD: Sorry for my english :C.
PD2: I'm working in Ubuntu 14.04 x64 .

**Comment by HBReview** [comment] 2016-06-09 17:25
could anybody help me to figure out this, i got an error again and again after running all things well

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn cmd ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)

**Comment by gulijiyag** [comment] 2016-08-04 19:51
I'm having the same problem, I don't press anything and the process continues running.

**Comment by tobyaries** [comment] 2016-08-31 06:01
I resoleved the problem just by installing the grunt modules...npm install -g grunt.

**Comment by hoangdangninh** [comment] 2016-12-01 06:08
same problem, ubuntu 16.04
