### ISSUE TITLE
Need IE=edge line in generated index.html?

### ISSUE THREAD

**Issue by devotis** [yeoman/generator-angular#1067] opened 2015-04-23 15:34 UTC
I have myself a webdev checklist. On it sits this instruction to myself. Do include IE=edge in the html header, like so:

    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome" />
It solves giving IE reasons to operate in any version lower than it can operate.

That meta line is not generated in index.html. Is that intentional, or should it be added?

**Comment by arthurvr** [comment] 2015-04-23 16:00
> IE=edge,chrome

both are deprecated :) refer to https://github.com/h5bp/html5-boilerplate/issues/1379 and https://msdn.microsoft.com/en-us/library/ie/dn384051%28v=vs.85%29.aspx.

**Comment by arthurvr** [comment] 2015-04-23 16:03
Also this is a duplicate of https://github.com/yeoman/generator-angular/pull/1032.

**Closed** 2015-04-23 16:32 UTC
