### ISSUE TITLE
when should support generate Components for lastest Angular 1.5

### ISSUE THREAD

**Issue by axetroy** [yeoman/generator-angular#1276] opened 2016-02-21 19:34 UTC
for more detail
it can be told in [Angular official website](https://docs.angularjs.org/guide/component)
the feature for transition to Angular2;
I think it is necessary;

**Comment by eddiemonge** [comment] 2016-02-22 22:51
duplicate of #1263

**Closed by eddiemonge** 2016-02-22 22:51 UTC
Labels: pr-welcome
