### ISSUE TITLE
usemin build bower:css bower:js not work when use gulp

### ISSUE THREAD

**Issue by leshin** [yeoman/generator-angular#1197] opened 2015-10-29 15:24 UTC

**Comment by arthurvr** [comment] 2015-10-29 15:27
Can you elaborate? Where is it going wrong? What versions are you using? What command did you use? What are you expecting it to do?

**Comment by leshin** [comment] 2015-10-29 15:37
Angular.js isn't load ! Error: Uncaught ReferenceError: angular is not defined.

**Comment by eddiemonge** [comment] 2015-10-29 19:12
What version of the generator are you using?

**Comment by ptrikutam** [comment] 2015-10-29 19:41
I'm having the same issue. Forgive my ignorance about the ecosystem of tools involved with this generator, and if I'm posting this in the wrong thread please let me know.

The first issue I saw was when running `yo angular`:

```
[12:33:20] Using gulpfile ~/Development/delete/gulpfile.js
[12:33:20] Task 'wiredep' is not in your gulpfile
[12:33:20] Please check the documentation for proper gulpfile formatting
```

Then, when when I try to run `gulp`:
```
$ gulp
[12:35:45] Using gulpfile ~/Development/delete/gulpfile.js
[12:35:45] Starting 'clean:dist'...
[12:35:45] Finished 'clean:dist' after 4.15 ms
[12:35:45] Starting 'build'...
[12:35:45] Starting 'images'...
[12:35:45] Starting 'copy:extras'...
[12:35:45] Starting 'copy:fonts'...
[12:35:45] Starting 'html'...
[12:35:45] Starting 'styles'...
[12:35:45] Finished 'build' after 272 ms
[12:35:45] Starting 'default'...
[12:35:45] Finished 'default' after 3.63 μs
[12:35:45] Finished 'copy:fonts' after 12 ms
[12:35:45] Finished 'copy:extras' after 18 ms
[12:35:45] Finished 'styles' after 80 ms
[12:35:45] Finished 'images' after 349 ms
[12:35:45] Finished 'html' after 84 ms
[12:35:45] Starting 'client:build'...
[12:35:46] 'client:build' errored after 432 ms
[12:35:46] TypeError: undefined is not a function
    at Gulp.<anonymous> (/Users/pavan/Development/delete/gulpfile.js:167:20)
    at module.exports (/Users/pavan/Development/delete/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/pavan/Development/delete/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/pavan/Development/delete/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at /Users/pavan/Development/delete/node_modules/gulp/node_modules/orchestrator/index.js:279:18
    at finish (/Users/pavan/Development/delete/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at /Users/pavan/Development/delete/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:52:4
    at f (/Users/pavan/Development/delete/node_modules/gulp/node_modules/orchestrator/node_modules/end-of-stream/node_modules/once/once.js:17:25)
    at DestroyableTransform.onend (/Users/pavan/Development/delete/node_modules/gulp/node_modules/orchestrator/node_modules/end-of-stream/index.js:31:18)
    at DestroyableTransform.emit (events.js:129:20)
    at /Users/pavan/Development/delete/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:965:16
    at process._tickCallback (node.js:355:11)
[12:35:46] Error in plugin 'run-sequence'
Message:
    An error occured in task 'client:build'.
```

`gulp serve` seems to run without errors. However, in the browser:

```
app.js:11 Uncaught ReferenceError: angular is not defined
main.js:10 Uncaught ReferenceError: angular is not defined
about.js:10 Uncaught ReferenceError: angular is not defined
```

I'm using `generator-angular@0.14.0` and `yo@1.4.8`

**Comment by leshin** [comment] 2015-10-30 02:43
I'm using generator-angular@0.14.0 and yo@1.4.8

**Comment by leshin** [comment] 2015-10-30 03:51
```
npm WARN EPEERINVALID gulp-karma@0.0.4 requires a peer of karma@>=0.10 <=0.13 but none was installed.
[11:46:38] Using gulpfile ~\Source\Projects\Web\Angular\yo-angular-gulp\gulpfile.js
[11:46:38] Task 'wiredep' is not in your gulpfile
[11:46:38] Please check the documentation for proper gulpfile formatting
? Overwrite package.json? overwrite
    force     package.json
   create     .travis.yml
npm WARN install Couldn't install optional dependency: Unsupported
```

**Comment by leshin** [comment] 2015-10-30 05:10
···
npm WARN EPEERINVALID gulp-karma@0.0.4 requires a peer of karma@>=0.10 <=0.13 but none was installed.
[13:04:10] Using gulpfile ~\Source\Projects\Web\Angular\yo-angular-gulp\gulpfile.js
[13:04:10] Task 'wiredep' is not in your gulpfile
[13:04:10] Please check the documentation for proper gulpfile formatting

C:\Users\XXX\Source\Projects\Web\Angular\yo-angular-gulp>gulp bower
[13:06:39] Using gulpfile ~\Source\Projects\Web\Angular\yo-angular-gulp\gulpfile.js
[13:06:39] Starting 'bower'...
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Error: angular is not installed. Try running `bower install`.
···

**Comment by eddiemonge** [comment] 2015-11-03 19:34
marking as duplicate of #1199

**Closed by eddiemonge** 2015-11-03 19:34 UTC
