### ISSUE TITLE
Connect livereload not working properly with html5mode

### ISSUE THREAD

**Issue by pensierinmusica** [yeoman/generator-angular#1043] opened 2015-03-22 17:41 UTC
Hi,

On projects generated with "generator-angular", if `html5mode` is set to `true`, running `grunt serve` does not properly handle routing on page reload. I guess that's because the "server" rules are not correctly implemented.

From [Angular docs](https://docs.angularjs.org/guide/$location):
> Using this mode requires URL rewriting on server side, basically you have to rewrite all your links to entry point of your application (e.g. index.html). Requiring a <base> tag is also important for this case, as it allows Angular to differentiate between the part of the url that is the application base and the path that should be handled by the application.

Could this be fixed? Thanks!

**Comment by eddiemonge** [comment] 2015-03-24 16:09
duplicate of #433

**Closed by eddiemonge** 2015-03-24 16:09 UTC
Labels: duplicate
